name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set actions
        uses: actions/checkout@v2
      - run: npm install
      - run: |
          git config --global user.email "basarozcan@gmail.com"
          git config --global user.name "basarozcan"
      - name: heroku deploy action
        uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dmv-mevn-seat-planner" #Must be unique in Heroku
          heroku_email: "basarozcan@gmail.com"
          appdir: "backend" # <- This will point to the api folder in your project
